In [1]:
import pandas as pd

a = [0, 5, 9]

myvar = pd.Series(a)

print(myvar)

0    0
1    5
2    9
dtype: int64

In [2]:
import pandas as pd

a = [0, 5, 9]

myvar = pd.Series(a)

print(myvar[0])

0

In [5]:
import pandas as pd

a = [10, 70, 20]

myvar = pd.Series(a, index = ["a", "b", "c"])

print(myvar)

a    10
b    70
c    20
dtype: int64

In [7]:
import pandas as pd

calories = {"Day1": 400, "Day2": 300, "Day3": 300}

myvar = pd.Series(calories)

print(myvar)

Day1    400
Day2    300
Day3    300
dtype: int64

In [8]:
import pandas as pd

calories = {"day1": 420, "day2": 380, "day3": 390}

myvar = pd.Series(calories, index = ["day1", "day2"])

print(myvar)

day1    420
day2    380
dtype: int64

In [6]:
import pandas as pd

data = {
  "flowers": ["rose", "lotus", "tulip"],
  "colors": ["blue", "pink", "red"]
}

myvar = pd.DataFrame(data)

print(myvar)

  flowers colors
0    rose   blue
1   lotus   pink
2   tulip    red

In [13]:
import pandas as pd

data = {
  "calories": [420, 380, 390],
  "duration": [50, 40, 45]
}

#load data into a DataFrame object:
df = pd.DataFrame(data)

import pandas as pd

data = {
  "calories": [420, 380, 390],
  "duration": [50, 40, 45]
}

#load data into a DataFrame object:
df = pd.DataFrame(data)

print(df.loc[[0, 1]])

   calories  duration
0       420        50
1       380        40

In [27]:
import pandas as pd

df = pd.read_csv('data.csv')

print(df.to_string())

    Duration  Pulse  Maxpulse  Calories        Date
0         60    110       130     409.1  01/01/2015
1         60    117       145     479.0  01/01/2015
2         60    103       135     340.0  02/01/2015
3         45    109       175     282.4  03/01/2015
4         45    117       148     406.0  04/01/2015
5         60    102       127     300.0  05/01/2015
6         60    110       136     374.0  06/01/2015
7         45    104       134     253.3  07/01/2015
8         30    109       133     195.1  08/01/2015
9         60     98       124     269.0  09/01/2015
10        60    103       147     329.3  10/01/2015
11        60    100       120     250.7  07/01/2015
12        60    106       128     345.3  12/01/2015
13        60    104       132     379.3  13/01/2015
14        60     98       123     275.0  14/01/2015
15        60     98       120     215.2  15/01/2015
16        60    100       120     300.0  15/01/2015
17        45     90       112       NaN  17/01/2015
18        60    103       123     323.0  18/01/2015
19        45     97       125     243.0  19/01/2015
20        60    108       131     364.2  20/01/2015
21        45    100       119     282.0  21/01/2015
22        60    130       101     300.0  22/01/2015
23        45    105       132     246.0  23/01/2015
24        60    102       126     334.5  24/01/2015
25        60    100       120     250.0  25/01/2015
26        60     92       118     241.0  21/01/2015
27        60    103       132       NaN  27/01/2015
28        60    100       132     280.0  28/01/2015
29        60    102       129     380.3  29/01/2015
30        60     92       115     243.0  30/01/2015
31        45     90       112     180.1  31/01/2015
32        60    101       124     299.0  01/02/2015
33        60     93       113     223.0  02/02/2015
34        60    107       136     361.0  03/02/2015
35        60    114       140     415.0  04/02/2015
36        60    102       127     300.0  05/02/2015
37        60    100       120     300.0  06/02/2015
38        60    100       120     300.0  07/02/2015
39        45    104       129     266.0  08/02/2015
40        45     90       112     180.1  09/02/2015
41        60     98       126     286.0  10/02/2015
42        60    100       122     329.4  11/02/2015
43        60    111       138     400.0  12/02/2015
44        60    111       131     397.0  13/02/2015
45        60     99       119     273.0  08/02/2015
46        60    109       153     387.6  15/02/2015
47        45    111       136     300.0  16/02/2015
48        45    108       129     298.0  17/02/2015

In [28]:

import pandas as pd

df = pd.read_csv('data.csv')

print(df)

    Duration  Pulse  Maxpulse  Calories        Date
0         60    110       130     409.1  01/01/2015
1         60    117       145     479.0  01/01/2015
2         60    103       135     340.0  02/01/2015
3         45    109       175     282.4  03/01/2015
4         45    117       148     406.0  04/01/2015
5         60    102       127     300.0  05/01/2015
6         60    110       136     374.0  06/01/2015
7         45    104       134     253.3  07/01/2015
8         30    109       133     195.1  08/01/2015
9         60     98       124     269.0  09/01/2015
10        60    103       147     329.3  10/01/2015
11        60    100       120     250.7  07/01/2015
12        60    106       128     345.3  12/01/2015
13        60    104       132     379.3  13/01/2015
14        60     98       123     275.0  14/01/2015
15        60     98       120     215.2  15/01/2015
16        60    100       120     300.0  15/01/2015
17        45     90       112       NaN  17/01/2015
18        60    103       123     323.0  18/01/2015
19        45     97       125     243.0  19/01/2015
20        60    108       131     364.2  20/01/2015
21        45    100       119     282.0  21/01/2015
22        60    130       101     300.0  22/01/2015
23        45    105       132     246.0  23/01/2015
24        60    102       126     334.5  24/01/2015
25        60    100       120     250.0  25/01/2015
26        60     92       118     241.0  21/01/2015
27        60    103       132       NaN  27/01/2015
28        60    100       132     280.0  28/01/2015
29        60    102       129     380.3  29/01/2015
30        60     92       115     243.0  30/01/2015
31        45     90       112     180.1  31/01/2015
32        60    101       124     299.0  01/02/2015
33        60     93       113     223.0  02/02/2015
34        60    107       136     361.0  03/02/2015
35        60    114       140     415.0  04/02/2015
36        60    102       127     300.0  05/02/2015
37        60    100       120     300.0  06/02/2015
38        60    100       120     300.0  07/02/2015
39        45    104       129     266.0  08/02/2015
40        45     90       112     180.1  09/02/2015
41        60     98       126     286.0  10/02/2015
42        60    100       122     329.4  11/02/2015
43        60    111       138     400.0  12/02/2015
44        60    111       131     397.0  13/02/2015
45        60     99       119     273.0  08/02/2015
46        60    109       153     387.6  15/02/2015
47        45    111       136     300.0  16/02/2015
48        45    108       129     298.0  17/02/2015

In [29]:
import pandas as pd

print(pd.options.display.max_rows)

60

In [30]:
import pandas as pd

df = pd.read_csv('data.csv')

print(df.head(10))

   Duration  Pulse  Maxpulse  Calories        Date
0        60    110       130     409.1  01/01/2015
1        60    117       145     479.0  01/01/2015
2        60    103       135     340.0  02/01/2015
3        45    109       175     282.4  03/01/2015
4        45    117       148     406.0  04/01/2015
5        60    102       127     300.0  05/01/2015
6        60    110       136     374.0  06/01/2015
7        45    104       134     253.3  07/01/2015
8        30    109       133     195.1  08/01/2015
9        60     98       124     269.0  09/01/2015

In [31]:
import pandas as pd

df = pd.read_csv('data.csv')

print(df.head())

   Duration  Pulse  Maxpulse  Calories        Date
0        60    110       130     409.1  01/01/2015
1        60    117       145     479.0  01/01/2015
2        60    103       135     340.0  02/01/2015
3        45    109       175     282.4  03/01/2015
4        45    117       148     406.0  04/01/2015

In [22]:
import pandas as pd

df = pd.read_csv('data.csv')

print(df.tail())

    Duration  Pulse  Maxpulse  Calories        Date
44        60    111       131     397.0  13/02/2015
45        60     99       119     273.0  08/02/2015
46        60    109       153     387.6  15/02/2015
47        45    111       136     300.0  16/02/2015
48        45    108       129     298.0  17/02/2015

In [32]:
import pandas as pd

df = pd.read_csv('data.csv')

print(df.tail(2))

    Duration  Pulse  Maxpulse  Calories        Date
47        45    111       136     300.0  16/02/2015
48        45    108       129     298.0  17/02/2015

In [33]:
import pandas as pd

df = pd.read_csv('data.csv')

df.dropna(inplace = True)

print(df.to_string())

    Duration  Pulse  Maxpulse  Calories        Date
0         60    110       130     409.1  01/01/2015
1         60    117       145     479.0  01/01/2015
2         60    103       135     340.0  02/01/2015
3         45    109       175     282.4  03/01/2015
4         45    117       148     406.0  04/01/2015
5         60    102       127     300.0  05/01/2015
6         60    110       136     374.0  06/01/2015
7         45    104       134     253.3  07/01/2015
8         30    109       133     195.1  08/01/2015
9         60     98       124     269.0  09/01/2015
10        60    103       147     329.3  10/01/2015
11        60    100       120     250.7  07/01/2015
12        60    106       128     345.3  12/01/2015
13        60    104       132     379.3  13/01/2015
14        60     98       123     275.0  14/01/2015
15        60     98       120     215.2  15/01/2015
16        60    100       120     300.0  15/01/2015
18        60    103       123     323.0  18/01/2015
19        45     97       125     243.0  19/01/2015
20        60    108       131     364.2  20/01/2015
21        45    100       119     282.0  21/01/2015
22        60    130       101     300.0  22/01/2015
23        45    105       132     246.0  23/01/2015
24        60    102       126     334.5  24/01/2015
25        60    100       120     250.0  25/01/2015
26        60     92       118     241.0  21/01/2015
28        60    100       132     280.0  28/01/2015
29        60    102       129     380.3  29/01/2015
30        60     92       115     243.0  30/01/2015
31        45     90       112     180.1  31/01/2015
32        60    101       124     299.0  01/02/2015
33        60     93       113     223.0  02/02/2015
34        60    107       136     361.0  03/02/2015
35        60    114       140     415.0  04/02/2015
36        60    102       127     300.0  05/02/2015
37        60    100       120     300.0  06/02/2015
38        60    100       120     300.0  07/02/2015
39        45    104       129     266.0  08/02/2015
40        45     90       112     180.1  09/02/2015
41        60     98       126     286.0  10/02/2015
42        60    100       122     329.4  11/02/2015
43        60    111       138     400.0  12/02/2015
44        60    111       131     397.0  13/02/2015
45        60     99       119     273.0  08/02/2015
46        60    109       153     387.6  15/02/2015
47        45    111       136     300.0  16/02/2015
48        45    108       129     298.0  17/02/2015

In [34]:
import pandas as pd

df = pd.read_csv('data.csv')

df.fillna(130, inplace = True) 
print(df.to_string())

    Duration  Pulse  Maxpulse  Calories        Date
0         60    110       130     409.1  01/01/2015
1         60    117       145     479.0  01/01/2015
2         60    103       135     340.0  02/01/2015
3         45    109       175     282.4  03/01/2015
4         45    117       148     406.0  04/01/2015
5         60    102       127     300.0  05/01/2015
6         60    110       136     374.0  06/01/2015
7         45    104       134     253.3  07/01/2015
8         30    109       133     195.1  08/01/2015
9         60     98       124     269.0  09/01/2015
10        60    103       147     329.3  10/01/2015
11        60    100       120     250.7  07/01/2015
12        60    106       128     345.3  12/01/2015
13        60    104       132     379.3  13/01/2015
14        60     98       123     275.0  14/01/2015
15        60     98       120     215.2  15/01/2015
16        60    100       120     300.0  15/01/2015
17        45     90       112     130.0  17/01/2015
18        60    103       123     323.0  18/01/2015
19        45     97       125     243.0  19/01/2015
20        60    108       131     364.2  20/01/2015
21        45    100       119     282.0  21/01/2015
22        60    130       101     300.0  22/01/2015
23        45    105       132     246.0  23/01/2015
24        60    102       126     334.5  24/01/2015
25        60    100       120     250.0  25/01/2015
26        60     92       118     241.0  21/01/2015
27        60    103       132     130.0  27/01/2015
28        60    100       132     280.0  28/01/2015
29        60    102       129     380.3  29/01/2015
30        60     92       115     243.0  30/01/2015
31        45     90       112     180.1  31/01/2015
32        60    101       124     299.0  01/02/2015
33        60     93       113     223.0  02/02/2015
34        60    107       136     361.0  03/02/2015
35        60    114       140     415.0  04/02/2015
36        60    102       127     300.0  05/02/2015
37        60    100       120     300.0  06/02/2015
38        60    100       120     300.0  07/02/2015
39        45    104       129     266.0  08/02/2015
40        45     90       112     180.1  09/02/2015
41        60     98       126     286.0  10/02/2015
42        60    100       122     329.4  11/02/2015
43        60    111       138     400.0  12/02/2015
44        60    111       131     397.0  13/02/2015
45        60     99       119     273.0  08/02/2015
46        60    109       153     387.6  15/02/2015
47        45    111       136     300.0  16/02/2015
48        45    108       129     298.0  17/02/2015

In [4]:
import pandas as pd

df = pd.read_csv('data.csv')

x = df["Calories"].mean()

df["Calories"].fillna(x) 
print(df.to_string())

    Duration  Pulse  Maxpulse  Calories        Date
0         60    110       130     409.1  01/01/2015
1         60    117       145     479.0  01/01/2015
2         60    103       135     340.0  02/01/2015
3         45    109       175     282.4  03/01/2015
4         45    117       148     406.0  04/01/2015
5         60    102       127     300.0  05/01/2015
6         60    110       136     374.0  06/01/2015
7         45    104       134     253.3  07/01/2015
8         30    109       133     195.1  08/01/2015
9         60     98       124     269.0  09/01/2015
10        60    103       147     329.3  10/01/2015
11        60    100       120     250.7  07/01/2015
12        60    106       128     345.3  12/01/2015
13        60    104       132     379.3  13/01/2015
14        60     98       123     275.0  14/01/2015
15        60     98       120     215.2  15/01/2015
16        60    100       120     300.0  15/01/2015
17        45     90       112       NaN  17/01/2015
18        60    103       123     323.0  18/01/2015
19        45     97       125     243.0  19/01/2015
20        60    108       131     364.2  20/01/2015
21        45    100       119     282.0  21/01/2015
22        60    130       101     300.0  22/01/2015
23        45    105       132     246.0  23/01/2015
24        60    102       126     334.5  24/01/2015
25        60    100       120     250.0  25/01/2015
26        60     92       118     241.0  21/01/2015
27        60    103       132       NaN  27/01/2015
28        60    100       132     280.0  28/01/2015
29        60    102       129     380.3  29/01/2015
30        60     92       115     243.0  30/01/2015
31        45     90       112     180.1  31/01/2015
32        60    101       124     299.0  01/02/2015
33        60     93       113     223.0  02/02/2015
34        60    107       136     361.0  03/02/2015
35        60    114       140     415.0  04/02/2015
36        60    102       127     300.0  05/02/2015
37        60    100       120     300.0  06/02/2015
38        60    100       120     300.0  07/02/2015
39        45    104       129     266.0  08/02/2015
40        45     90       112     180.1  09/02/2015
41        60     98       126     286.0  10/02/2015
42        60    100       122     329.4  11/02/2015
43        60    111       138     400.0  12/02/2015
44        60    111       131     397.0  13/02/2015
45        60     99       119     273.0  08/02/2015
46        60    109       153     387.6  15/02/2015
47        45    111       136     300.0  16/02/2015
48        45    108       129     298.0  17/02/2015

In [3]:
import pandas as pd

df = pd.read_csv('data.csv')

x = df["Calories"].median()


df["Calories"] = df["Calories"].fillna(x) 

print(df.to_string())

    Duration  Pulse  Maxpulse  Calories        Date
0         60    110       130     409.1  01/01/2015
1         60    117       145     479.0  01/01/2015
2         60    103       135     340.0  02/01/2015
3         45    109       175     282.4  03/01/2015
4         45    117       148     406.0  04/01/2015
5         60    102       127     300.0  05/01/2015
6         60    110       136     374.0  06/01/2015
7         45    104       134     253.3  07/01/2015
8         30    109       133     195.1  08/01/2015
9         60     98       124     269.0  09/01/2015
10        60    103       147     329.3  10/01/2015
11        60    100       120     250.7  07/01/2015
12        60    106       128     345.3  12/01/2015
13        60    104       132     379.3  13/01/2015
14        60     98       123     275.0  14/01/2015
15        60     98       120     215.2  15/01/2015
16        60    100       120     300.0  15/01/2015
17        45     90       112     300.0  17/01/2015
18        60    103       123     323.0  18/01/2015
19        45     97       125     243.0  19/01/2015
20        60    108       131     364.2  20/01/2015
21        45    100       119     282.0  21/01/2015
22        60    130       101     300.0  22/01/2015
23        45    105       132     246.0  23/01/2015
24        60    102       126     334.5  24/01/2015
25        60    100       120     250.0  25/01/2015
26        60     92       118     241.0  21/01/2015
27        60    103       132     300.0  27/01/2015
28        60    100       132     280.0  28/01/2015
29        60    102       129     380.3  29/01/2015
30        60     92       115     243.0  30/01/2015
31        45     90       112     180.1  31/01/2015
32        60    101       124     299.0  01/02/2015
33        60     93       113     223.0  02/02/2015
34        60    107       136     361.0  03/02/2015
35        60    114       140     415.0  04/02/2015
36        60    102       127     300.0  05/02/2015
37        60    100       120     300.0  06/02/2015
38        60    100       120     300.0  07/02/2015
39        45    104       129     266.0  08/02/2015
40        45     90       112     180.1  09/02/2015
41        60     98       126     286.0  10/02/2015
42        60    100       122     329.4  11/02/2015
43        60    111       138     400.0  12/02/2015
44        60    111       131     397.0  13/02/2015
45        60     99       119     273.0  08/02/2015
46        60    109       153     387.6  15/02/2015
47        45    111       136     300.0  16/02/2015
48        45    108       129     298.0  17/02/2015

In [4]:
import pandas as pd

df = pd.read_csv('data.csv')

x = df["Calories"].mode()[0]


df["Calories"] = df["Calories"].fillna(x)

print(df.to_string())

    Duration  Pulse  Maxpulse  Calories        Date
0         60    110       130     409.1  01/01/2015
1         60    117       145     479.0  01/01/2015
2         60    103       135     340.0  02/01/2015
3         45    109       175     282.4  03/01/2015
4         45    117       148     406.0  04/01/2015
5         60    102       127     300.0  05/01/2015
6         60    110       136     374.0  06/01/2015
7         45    104       134     253.3  07/01/2015
8         30    109       133     195.1  08/01/2015
9         60     98       124     269.0  09/01/2015
10        60    103       147     329.3  10/01/2015
11        60    100       120     250.7  07/01/2015
12        60    106       128     345.3  12/01/2015
13        60    104       132     379.3  13/01/2015
14        60     98       123     275.0  14/01/2015
15        60     98       120     215.2  15/01/2015
16        60    100       120     300.0  15/01/2015
17        45     90       112     300.0  17/01/2015
18        60    103       123     323.0  18/01/2015
19        45     97       125     243.0  19/01/2015
20        60    108       131     364.2  20/01/2015
21        45    100       119     282.0  21/01/2015
22        60    130       101     300.0  22/01/2015
23        45    105       132     246.0  23/01/2015
24        60    102       126     334.5  24/01/2015
25        60    100       120     250.0  25/01/2015
26        60     92       118     241.0  21/01/2015
27        60    103       132     300.0  27/01/2015
28        60    100       132     280.0  28/01/2015
29        60    102       129     380.3  29/01/2015
30        60     92       115     243.0  30/01/2015
31        45     90       112     180.1  31/01/2015
32        60    101       124     299.0  01/02/2015
33        60     93       113     223.0  02/02/2015
34        60    107       136     361.0  03/02/2015
35        60    114       140     415.0  04/02/2015
36        60    102       127     300.0  05/02/2015
37        60    100       120     300.0  06/02/2015
38        60    100       120     300.0  07/02/2015
39        45    104       129     266.0  08/02/2015
40        45     90       112     180.1  09/02/2015
41        60     98       126     286.0  10/02/2015
42        60    100       122     329.4  11/02/2015
43        60    111       138     400.0  12/02/2015
44        60    111       131     397.0  13/02/2015
45        60     99       119     273.0  08/02/2015
46        60    109       153     387.6  15/02/2015
47        45    111       136     300.0  16/02/2015
48        45    108       129     298.0  17/02/2015

In [5]:
import pandas as pd

df = pd.read_csv('data.csv')


df['Date'] = pd.to_datetime(df['Date'], format='%d/%m/%Y')

print(df.to_string())

    Duration  Pulse  Maxpulse  Calories       Date
0         60    110       130     409.1 2015-01-01
1         60    117       145     479.0 2015-01-01
2         60    103       135     340.0 2015-01-02
3         45    109       175     282.4 2015-01-03
4         45    117       148     406.0 2015-01-04
5         60    102       127     300.0 2015-01-05
6         60    110       136     374.0 2015-01-06
7         45    104       134     253.3 2015-01-07
8         30    109       133     195.1 2015-01-08
9         60     98       124     269.0 2015-01-09
10        60    103       147     329.3 2015-01-10
11        60    100       120     250.7 2015-01-07
12        60    106       128     345.3 2015-01-12
13        60    104       132     379.3 2015-01-13
14        60     98       123     275.0 2015-01-14
15        60     98       120     215.2 2015-01-15
16        60    100       120     300.0 2015-01-15
17        45     90       112       NaN 2015-01-17
18        60    103       123     323.0 2015-01-18
19        45     97       125     243.0 2015-01-19
20        60    108       131     364.2 2015-01-20
21        45    100       119     282.0 2015-01-21
22        60    130       101     300.0 2015-01-22
23        45    105       132     246.0 2015-01-23
24        60    102       126     334.5 2015-01-24
25        60    100       120     250.0 2015-01-25
26        60     92       118     241.0 2015-01-21
27        60    103       132       NaN 2015-01-27
28        60    100       132     280.0 2015-01-28
29        60    102       129     380.3 2015-01-29
30        60     92       115     243.0 2015-01-30
31        45     90       112     180.1 2015-01-31
32        60    101       124     299.0 2015-02-01
33        60     93       113     223.0 2015-02-02
34        60    107       136     361.0 2015-02-03
35        60    114       140     415.0 2015-02-04
36        60    102       127     300.0 2015-02-05
37        60    100       120     300.0 2015-02-06
38        60    100       120     300.0 2015-02-07
39        45    104       129     266.0 2015-02-08
40        45     90       112     180.1 2015-02-09
41        60     98       126     286.0 2015-02-10
42        60    100       122     329.4 2015-02-11
43        60    111       138     400.0 2015-02-12
44        60    111       131     397.0 2015-02-13
45        60     99       119     273.0 2015-02-08
46        60    109       153     387.6 2015-02-15
47        45    111       136     300.0 2015-02-16
48        45    108       129     298.0 2015-02-17

In [8]:
import pandas as pd

df = pd.read_csv('data.csv')


df['Date'] = pd.to_datetime(df['Date'], dayfirst=True)

df.dropna(subset=['Date'], inplace=True)

print(df.to_string())

    Duration  Pulse  Maxpulse  Calories       Date
0         60    110       130     409.1 2015-01-01
1         60    117       145     479.0 2015-01-01
2         60    103       135     340.0 2015-01-02
3         45    109       175     282.4 2015-01-03
4         45    117       148     406.0 2015-01-04
5         60    102       127     300.0 2015-01-05
6         60    110       136     374.0 2015-01-06
7         45    104       134     253.3 2015-01-07
8         30    109       133     195.1 2015-01-08
9         60     98       124     269.0 2015-01-09
10        60    103       147     329.3 2015-01-10
11        60    100       120     250.7 2015-01-07
12        60    106       128     345.3 2015-01-12
13        60    104       132     379.3 2015-01-13
14        60     98       123     275.0 2015-01-14
15        60     98       120     215.2 2015-01-15
16        60    100       120     300.0 2015-01-15
17        45     90       112       NaN 2015-01-17
18        60    103       123     323.0 2015-01-18
19        45     97       125     243.0 2015-01-19
20        60    108       131     364.2 2015-01-20
21        45    100       119     282.0 2015-01-21
22        60    130       101     300.0 2015-01-22
23        45    105       132     246.0 2015-01-23
24        60    102       126     334.5 2015-01-24
25        60    100       120     250.0 2015-01-25
26        60     92       118     241.0 2015-01-21
27        60    103       132       NaN 2015-01-27
28        60    100       132     280.0 2015-01-28
29        60    102       129     380.3 2015-01-29
30        60     92       115     243.0 2015-01-30
31        45     90       112     180.1 2015-01-31
32        60    101       124     299.0 2015-02-01
33        60     93       113     223.0 2015-02-02
34        60    107       136     361.0 2015-02-03
35        60    114       140     415.0 2015-02-04
36        60    102       127     300.0 2015-02-05
37        60    100       120     300.0 2015-02-06
38        60    100       120     300.0 2015-02-07
39        45    104       129     266.0 2015-02-08
40        45     90       112     180.1 2015-02-09
41        60     98       126     286.0 2015-02-10
42        60    100       122     329.4 2015-02-11
43        60    111       138     400.0 2015-02-12
44        60    111       131     397.0 2015-02-13
45        60     99       119     273.0 2015-02-08
46        60    109       153     387.6 2015-02-15
47        45    111       136     300.0 2015-02-16
48        45    108       129     298.0 2015-02-17

In [9]:
import pandas as pd

df = pd.read_csv('data.csv')

df.loc[7,'Duration'] = 45

print(df.to_string())

    Duration  Pulse  Maxpulse  Calories        Date
0         60    110       130     409.1  01/01/2015
1         60    117       145     479.0  01/01/2015
2         60    103       135     340.0  02/01/2015
3         45    109       175     282.4  03/01/2015
4         45    117       148     406.0  04/01/2015
5         60    102       127     300.0  05/01/2015
6         60    110       136     374.0  06/01/2015
7         45    104       134     253.3  07/01/2015
8         30    109       133     195.1  08/01/2015
9         60     98       124     269.0  09/01/2015
10        60    103       147     329.3  10/01/2015
11        60    100       120     250.7  07/01/2015
12        60    106       128     345.3  12/01/2015
13        60    104       132     379.3  13/01/2015
14        60     98       123     275.0  14/01/2015
15        60     98       120     215.2  15/01/2015
16        60    100       120     300.0  15/01/2015
17        45     90       112       NaN  17/01/2015
18        60    103       123     323.0  18/01/2015
19        45     97       125     243.0  19/01/2015
20        60    108       131     364.2  20/01/2015
21        45    100       119     282.0  21/01/2015
22        60    130       101     300.0  22/01/2015
23        45    105       132     246.0  23/01/2015
24        60    102       126     334.5  24/01/2015
25        60    100       120     250.0  25/01/2015
26        60     92       118     241.0  21/01/2015
27        60    103       132       NaN  27/01/2015
28        60    100       132     280.0  28/01/2015
29        60    102       129     380.3  29/01/2015
30        60     92       115     243.0  30/01/2015
31        45     90       112     180.1  31/01/2015
32        60    101       124     299.0  01/02/2015
33        60     93       113     223.0  02/02/2015
34        60    107       136     361.0  03/02/2015
35        60    114       140     415.0  04/02/2015
36        60    102       127     300.0  05/02/2015
37        60    100       120     300.0  06/02/2015
38        60    100       120     300.0  07/02/2015
39        45    104       129     266.0  08/02/2015
40        45     90       112     180.1  09/02/2015
41        60     98       126     286.0  10/02/2015
42        60    100       122     329.4  11/02/2015
43        60    111       138     400.0  12/02/2015
44        60    111       131     397.0  13/02/2015
45        60     99       119     273.0  08/02/2015
46        60    109       153     387.6  15/02/2015
47        45    111       136     300.0  16/02/2015
48        45    108       129     298.0  17/02/2015

In [10]:
import pandas as pd

df = pd.read_csv('data.csv')

for x in df.index:
      if df.loc[x, "Duration"] > 120:
        df.loc[x, "Duration"] = 120

print(df.to_string())

    Duration  Pulse  Maxpulse  Calories        Date
0         60    110       130     409.1  01/01/2015
1         60    117       145     479.0  01/01/2015
2         60    103       135     340.0  02/01/2015
3         45    109       175     282.4  03/01/2015
4         45    117       148     406.0  04/01/2015
5         60    102       127     300.0  05/01/2015
6         60    110       136     374.0  06/01/2015
7         45    104       134     253.3  07/01/2015
8         30    109       133     195.1  08/01/2015
9         60     98       124     269.0  09/01/2015
10        60    103       147     329.3  10/01/2015
11        60    100       120     250.7  07/01/2015
12        60    106       128     345.3  12/01/2015
13        60    104       132     379.3  13/01/2015
14        60     98       123     275.0  14/01/2015
15        60     98       120     215.2  15/01/2015
16        60    100       120     300.0  15/01/2015
17        45     90       112       NaN  17/01/2015
18        60    103       123     323.0  18/01/2015
19        45     97       125     243.0  19/01/2015
20        60    108       131     364.2  20/01/2015
21        45    100       119     282.0  21/01/2015
22        60    130       101     300.0  22/01/2015
23        45    105       132     246.0  23/01/2015
24        60    102       126     334.5  24/01/2015
25        60    100       120     250.0  25/01/2015
26        60     92       118     241.0  21/01/2015
27        60    103       132       NaN  27/01/2015
28        60    100       132     280.0  28/01/2015
29        60    102       129     380.3  29/01/2015
30        60     92       115     243.0  30/01/2015
31        45     90       112     180.1  31/01/2015
32        60    101       124     299.0  01/02/2015
33        60     93       113     223.0  02/02/2015
34        60    107       136     361.0  03/02/2015
35        60    114       140     415.0  04/02/2015
36        60    102       127     300.0  05/02/2015
37        60    100       120     300.0  06/02/2015
38        60    100       120     300.0  07/02/2015
39        45    104       129     266.0  08/02/2015
40        45     90       112     180.1  09/02/2015
41        60     98       126     286.0  10/02/2015
42        60    100       122     329.4  11/02/2015
43        60    111       138     400.0  12/02/2015
44        60    111       131     397.0  13/02/2015
45        60     99       119     273.0  08/02/2015
46        60    109       153     387.6  15/02/2015
47        45    111       136     300.0  16/02/2015
48        45    108       129     298.0  17/02/2015

In [11]:
import pandas as pd

df = pd.read_csv('data.csv')

print(df.duplicated())

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18     True
19    False
20    False
21    False
22    False
23     True
24    False
25    False
26     True
27    False
28     True
29    False
30    False
31    False
32    False
33     True
34    False
35    False
36    False
37    False
38    False
39    False
40    False
41    False
42    False
43    False
44    False
45    False
46    False
47    False
48    False
dtype: bool

In [15]:
import pandas as pd

df = pd.read_csv('data.csv')

numeric_df = df.select_dtypes(include=[float, int])

print(numeric_df.corr())

          Duration     Pulse  Maxpulse  Calories
Duration  1.000000  0.082908 -0.090335  0.480088
Pulse     0.082908  1.000000  0.418519  0.630635
Maxpulse -0.090335  0.418519  1.000000  0.483819
Calories  0.480088  0.630635  0.483819  1.000000